// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// did_cohort_att
Rcpp::List did_cohort_att(const Rcpp::IntegerVector& id, const Rcpp::IntegerVector& t, const Rcpp::NumericVector& y, const Rcpp::IntegerVector& g, const int L, const int F, const double min_cov);
RcppExport SEXP _syntheticdid_did_cohort_att(SEXP idSEXP, SEXP tSEXP, SEXP ySEXP, SEXP gSEXP, SEXP LSEXP, SEXP FSEXP, SEXP min_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type F(FSEXP);
    Rcpp::traits::input_parameter< const double >::type min_cov(min_covSEXP);
    rcpp_result_gen = Rcpp::wrap(did_cohort_att(id, t, y, g, L, F, min_cov));
    return rcpp_result_gen;
END_RCPP
}
// sc_pg_simplex
Rcpp::NumericVector sc_pg_simplex(const arma::mat& X, const arma::vec& y, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_sc_pg_simplex(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_pg_simplex(X, y, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// sc_pg_simplex_cov
Rcpp::NumericVector sc_pg_simplex_cov(const arma::mat& X, const arma::vec& y, const arma::mat& Z, const arma::vec& z, const double kappa, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_sc_pg_simplex_cov(SEXP XSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP zSEXP, SEXP kappaSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_pg_simplex_cov(X, y, Z, z, kappa, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// time_weights_pg
Rcpp::NumericVector time_weights_pg(const arma::vec& mu, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_time_weights_pg(SEXP muSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(time_weights_pg(mu, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// sdid_panel_att
Rcpp::List sdid_panel_att(const Rcpp::IntegerVector& id, const Rcpp::IntegerVector& t, const Rcpp::NumericVector& y, const Rcpp::IntegerVector& g, const int L, const int F, const double min_cov, const double lambda_unit, const double lambda_time, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_sdid_panel_att(SEXP idSEXP, SEXP tSEXP, SEXP ySEXP, SEXP gSEXP, SEXP LSEXP, SEXP FSEXP, SEXP min_covSEXP, SEXP lambda_unitSEXP, SEXP lambda_timeSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type F(FSEXP);
    Rcpp::traits::input_parameter< const double >::type min_cov(min_covSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_unit(lambda_unitSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_time(lambda_timeSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sdid_panel_att(id, t, y, g, L, F, min_cov, lambda_unit, lambda_time, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_syntheticdid_did_cohort_att", (DL_FUNC) &_syntheticdid_did_cohort_att, 7},
    {"_syntheticdid_sc_pg_simplex", (DL_FUNC) &_syntheticdid_sc_pg_simplex, 5},
    {"_syntheticdid_sc_pg_simplex_cov", (DL_FUNC) &_syntheticdid_sc_pg_simplex_cov, 8},
    {"_syntheticdid_time_weights_pg", (DL_FUNC) &_syntheticdid_time_weights_pg, 4},
    {"_syntheticdid_sdid_panel_att", (DL_FUNC) &_syntheticdid_sdid_panel_att, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_syntheticdid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
