// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// did_cohort_att
Rcpp::List did_cohort_att(const Rcpp::IntegerVector& id, const Rcpp::IntegerVector& t, const Rcpp::NumericVector& y, const Rcpp::IntegerVector& g, const int L, const int F, const double min_cov);
RcppExport SEXP _syntheticdid_did_cohort_att(SEXP idSEXP, SEXP tSEXP, SEXP ySEXP, SEXP gSEXP, SEXP LSEXP, SEXP FSEXP, SEXP min_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type F(FSEXP);
    Rcpp::traits::input_parameter< const double >::type min_cov(min_covSEXP);
    rcpp_result_gen = Rcpp::wrap(did_cohort_att(id, t, y, g, L, F, min_cov));
    return rcpp_result_gen;
END_RCPP
}
// sc_pg_simplex
Rcpp::NumericVector sc_pg_simplex(const arma::mat& X, const arma::vec& y, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_sc_pg_simplex(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_pg_simplex(X, y, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// sc_pg_simplex_cov
Rcpp::NumericVector sc_pg_simplex_cov(const arma::mat& X, const arma::vec& y, const arma::mat& Z, const arma::vec& z, const double kappa, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_sc_pg_simplex_cov(SEXP XSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP zSEXP, SEXP kappaSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_pg_simplex_cov(X, y, Z, z, kappa, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// time_weights_pg
Rcpp::NumericVector time_weights_pg(const arma::vec& mu, const double lambda, const int maxit, const double tol);
RcppExport SEXP _syntheticdid_time_weights_pg(SEXP muSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(time_weights_pg(mu, lambda, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// sdid_fit_cohort
Rcpp::List sdid_fit_cohort(const arma::mat& Y_T_pre, const arma::mat& Y_D_pre, const arma::mat& Y_T_post, const arma::mat& Y_D_post, const double lambda_unit, const bool use_unit_default, const double lambda_time, const bool use_time_default, const int maxit, const double tol, const double min_decrease, const bool use_min_default, const Rcpp::NumericVector& unit_warm, const Rcpp::NumericVector& time_warm);
RcppExport SEXP _syntheticdid_sdid_fit_cohort(SEXP Y_T_preSEXP, SEXP Y_D_preSEXP, SEXP Y_T_postSEXP, SEXP Y_D_postSEXP, SEXP lambda_unitSEXP, SEXP use_unit_defaultSEXP, SEXP lambda_timeSEXP, SEXP use_time_defaultSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP min_decreaseSEXP, SEXP use_min_defaultSEXP, SEXP unit_warmSEXP, SEXP time_warmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_T_pre(Y_T_preSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_D_pre(Y_D_preSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_T_post(Y_T_postSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_D_post(Y_D_postSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_unit(lambda_unitSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_unit_default(use_unit_defaultSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_time(lambda_timeSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_time_default(use_time_defaultSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type min_decrease(min_decreaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_min_default(use_min_defaultSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type unit_warm(unit_warmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type time_warm(time_warmSEXP);
    rcpp_result_gen = Rcpp::wrap(sdid_fit_cohort(Y_T_pre, Y_D_pre, Y_T_post, Y_D_post, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default, unit_warm, time_warm));
    return rcpp_result_gen;
END_RCPP
}
// sdid_panel_att
Rcpp::List sdid_panel_att(const Rcpp::IntegerVector& id, const Rcpp::IntegerVector& t, const Rcpp::NumericVector& y, const Rcpp::IntegerVector& g, const int L, const int F, const double min_cov, const double lambda_unit, const bool use_unit_default, const double lambda_time, const bool use_time_default, const int maxit, const double tol, const double min_decrease, const bool use_min_default);
RcppExport SEXP _syntheticdid_sdid_panel_att(SEXP idSEXP, SEXP tSEXP, SEXP ySEXP, SEXP gSEXP, SEXP LSEXP, SEXP FSEXP, SEXP min_covSEXP, SEXP lambda_unitSEXP, SEXP use_unit_defaultSEXP, SEXP lambda_timeSEXP, SEXP use_time_defaultSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP min_decreaseSEXP, SEXP use_min_defaultSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type F(FSEXP);
    Rcpp::traits::input_parameter< const double >::type min_cov(min_covSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_unit(lambda_unitSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_unit_default(use_unit_defaultSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_time(lambda_timeSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_time_default(use_time_defaultSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type min_decrease(min_decreaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_min_default(use_min_defaultSEXP);
    rcpp_result_gen = Rcpp::wrap(sdid_panel_att(id, t, y, g, L, F, min_cov, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_syntheticdid_did_cohort_att", (DL_FUNC) &_syntheticdid_did_cohort_att, 7},
    {"_syntheticdid_sc_pg_simplex", (DL_FUNC) &_syntheticdid_sc_pg_simplex, 5},
    {"_syntheticdid_sc_pg_simplex_cov", (DL_FUNC) &_syntheticdid_sc_pg_simplex_cov, 8},
    {"_syntheticdid_time_weights_pg", (DL_FUNC) &_syntheticdid_time_weights_pg, 4},
    {"_syntheticdid_sdid_fit_cohort", (DL_FUNC) &_syntheticdid_sdid_fit_cohort, 14},
    {"_syntheticdid_sdid_panel_att", (DL_FUNC) &_syntheticdid_sdid_panel_att, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_syntheticdid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
