# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.did_cohort_att <- function(id, t, y, g, L, F, min_cov) {
    .Call(`_syntheticdid_did_cohort_att`, id, t, y, g, L, F, min_cov)
}

.sc_pg_simplex <- function(X, y, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_sc_pg_simplex`, X, y, lambda, maxit, tol)
}

.sc_pg_simplex_cov <- function(X, y, Z, z, kappa = 1e-2, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_sc_pg_simplex_cov`, X, y, Z, z, kappa, lambda, maxit, tol)
}

.time_weights_pg <- function(mu, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_time_weights_pg`, mu, lambda, maxit, tol)
}

.sdid_panel_att <- function(id, t, y, g, L, F, min_cov, lambda_unit, lambda_time, maxit, tol) {
    .Call(`_syntheticdid_sdid_panel_att`, id, t, y, g, L, F, min_cov, lambda_unit, lambda_time, maxit, tol)
}

