# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.did_cohort_att <- function(id, t, y, g, L, F, min_cov) {
    .Call(`_syntheticdid_did_cohort_att`, id, t, y, g, L, F, min_cov)
}

.sc_pg_simplex <- function(X, y, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_sc_pg_simplex`, X, y, lambda, maxit, tol)
}

.sc_pg_simplex_cov <- function(X, y, Z, z, kappa = 1e-2, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_sc_pg_simplex_cov`, X, y, Z, z, kappa, lambda, maxit, tol)
}

.time_weights_pg <- function(mu, lambda = 1e-3, maxit = 5000L, tol = 1e-8) {
    .Call(`_syntheticdid_time_weights_pg`, mu, lambda, maxit, tol)
}

.sdid_fit_cohort <- function(Y_T_pre, Y_D_pre, Y_T_post, Y_D_post, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default, unit_warm, time_warm) {
    .Call(`_syntheticdid_sdid_fit_cohort`, Y_T_pre, Y_D_pre, Y_T_post, Y_D_post, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default, unit_warm, time_warm)
}

.sdid_panel_att <- function(id, t, y, g, L, F, min_cov, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default) {
    .Call(`_syntheticdid_sdid_panel_att`, id, t, y, g, L, F, min_cov, lambda_unit, use_unit_default, lambda_time, use_time_default, maxit, tol, min_decrease, use_min_default)
}

